version: '3'
services:
  
 gvm10:
    image: falkowich/gvm10:psql
    ports: 
      - 443:443
    restart: always
    volumes:
      - gvm:/usr/local/var/lib/gvm/
      - psql:/var/lib/postgresql/data
volumes:
  gvm:
  psql: