version: '3'
services:
  
  gvm10:
    image: falkowich/gvm10:sqlite-latest
    ports: 
      - 443:443
      - 9391:9391
    restart: always
    volumes:
      - gvm:/usr/local/var/lib/gvm/

volumes:
  gvm:
